# Generated by Django 3.2.9 on 2021-12-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_child_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='child_projects',
            new_name='parent_projects',
        ),
    ]
