# Generated by Django 3.2.9 on 2021-12-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_child_projects_project_parent_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='parent_projects',
            new_name='parent_project',
        ),
    ]
